openapi: 3.0.1
info:
  title: BookdataAPI
  description: Search books by either ISBN number or authors, OAS3
  contact:
    name: Johan Kjellin
    email: v3x0r_x014@hotmail.com
  version: '1.12'
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Get books
    description: Search the library for books
paths:
  '/book/isbn/{ISBN}':
    get:
      tags:
        - Get books
      parameters:
        - in: path
          name: ISBN
          description: 'ISBN is an ID for the book, examples are 1597800449 and 0762427329'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Success, found book'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        '400':
          description: Bad request error
        '403':
          description: Not allowed request
        '404':
          description: Book not found
  '/books/authors/{AUTHORS}':
    get:
      tags:
        - Get books
      parameters:
        - name: AUTHORS
          in: path
          description: >-
            Seachs by authors to find all books by the authors, could be several
            books
          required: true
          schema:
            type: string
          example: "shakespeare"
      responses:
        '200':
          description: 'Success, found book'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        '400':
          description: Bad request error
        '403':
          description: Not allowed request
        '404':
          description: Book not found
components:
  schemas:
    book:
      type: object
      properties:
        LanguageCode:
          type: string
          maximum: 9
          example: "eng"
        Reviews:
          type: integer
          minimum: 0
          maximum: 99999
          example: 535
        BookID:
          type: integer
          minimum: 1
          maximum: 99999
          example: 12009
        ISBN:
          type: integer
          minimum: 1
          maximum: 9999999999
          example: 1597800449
        AverageRating:
          type: number
          minimum: 1
          maximum: 5
          example: 4.01
        Authors:
          type: string
          minimum: 3
          maximum: 100
          example: "Iain M. Banks"
        NumPages:
          type: integer
          minimum: 1
          maximum: 99999
          example: 434
        Title:
          type: string
          minimum: 1
          maximum: 100
          example: "The Algebraist"
        ISBN13:
          type: number
          minimum: 1
          maximum: 9999999999999
          example: 9781597800440
        Ratings:
          type: integer
          minimum: 1
          maximum: 99999
          example: 14737