openapi: 3.0.1
info:
  title: bookdata API
  description: A database of books, searchable by isbn or authors
  version: 1.0.0
  contact:
    name: Bookdata API Support
    email: v3x0r_x014@hotmail.com

server: 'http://localhost:8080/api/v1'
servers:
  - url: '{protocol}://localhost:{port}/api/v1'
    variables:
      port:
        enum:
          - '8080'
          - '4444'
        default: '8080'
      protocol:
        default: http

host: 'localhost:8080'
basePath: '/api/v1'

schemes:
- "http"

tags:
- name: "Get books"
  description: "Search the library of 15k books"
- name: "Post book"
  description: "Add a new book to the Book API"


paths:
  /books/authors/{AUTHORS}:
    get:
      tags:
      - "Get books"
      summary: Get books by searching for authors
      parameters:
        - in: path
          name: AUTHORS
          schema:
            type: string
          required: true
          description: Author string to search books by
      description: Get book by name of authors
      responses:
        '200':
          description: success message retrieved when books are found
        '400':
          description: Bad Request
        '403':
          description: Forbidden message
        '404':
          description: Missing record means no books found with searched author

  /api/v1/book/isbn/{ISBN}:
    get:
      tags:
      - "Get books"
      summary: Get Book by ISBN, max 10 numbers
      parameters:
        - in: path
          name: ISBN
          schema:
            type: integer
          required: true
          description: ISBN number to search books with
      description: get book by entering its ISBN
      responses:
        '200':
          description: success message retrieved when books are found

  /api/v1/book:
    post:
      tags:
      - "Post book"
      description: Post a new book to the bookdata API
      requestBody:
        description: Parameters passed by json
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/schema/Book'
      responses:
        '201':
          description: Book has been added to database

definitions:
  schema:
    Book:
      type: "object"
      properties:
        LanguageCode:
          type: string
        Reviews:
          type: integer
        BookID:
          type: integer
        ISBN:
          type: integer
        AverageRating:
          type: number
        Authors:
          type: string
        NumPages:
          type: integer
        Title:
          type: string
        ISBN13:
          type: number
        Ratings:
          type: integer
