swagger: "2.0"
info:
  description: "This is a sample Bookdata API. You can find out more about     Swagger at swagger.io"
  version: "1.0.0"
  title: "Bookdata API"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "localhost:8080"
basePath: "/api/v1"

tags:
- name: "Get books"
  description: "Everything about books"
schemes:
- "https"
- "http"

paths:
  /book/{ISBN}:
    get:
      tags:
      - "Get books"
      summary: Find book by ISBN
      description: Returns a single book
      operationId: "searchByISBN"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "ISBN"
        in: "path"
        description: "ISBN of book to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Book not found"

  /books/authors/{AUTHORS}:
    get:
      tags: 
      - Get books
      summary: Get books by searching for authors, could be several matches
      description: Get a book by name of authors
      parameters:
        - in: path
          name: AUTHORS
          description: Author variable to search books with
          required: true
          type: string
      responses:
        '200':
          description: success message when books are found
        '400':
          description: Bad Request
        '403':
          description: Forbidden message recieved
        '404':
          description: Missing record means no books found with searched author

definitions:
  Book:
    type: "object"
    properties:
      LanguageCode:
        type: string
      Reviews:
        type: integer
      BookID:
        type: integer
      ISBN:
        type: integer
      AverageRating:
        type: number
      Authors:
        type: string
      NumPages:
        type: integer
      Title:
        type: string
      ISBN13:
        type: number
      Ratings:
        type: integer
