swagger: '2.0'
info:
  version: '1.0'
  title: BookdataAPI
  description: Search books by either ISBN number or authors
  contact:
    name: Johan Kjellin
    email: v3x0r_x014@hotmail.com
host: 'localhost:8080'
basePath: /api/v1
schemes:
  - http
tags:
  - name: Get books
    description: Search the library for books
paths:
  '/book/isbn/{ISBN}':
    get:
      tags:
        - Get books
      produces:
        - application/json
      parameters:
        - in: path
          name: ISBN
          description: 'ISBN is an ID for the book, examples are 1597800449 and 0762427329'
          required: true
          type: string
      responses:
        '200':
          description: 'Success, found book'
        '404':
          description: Book not found
  '/books/authors/{AUTHORS}':
    get:
      tags:
        - Get books
      produces:
        - application/json
      parameters:
        - in: path
          name: AUTHORS
          description: >-
            Seachs by authors to find all books by the authors, could be several
            books
          required: true
          type: string
      responses:
        '200':
          description: 'Success, found book'
        '404':
          description: Book not found
